version: 0.3.0.{build}

environment:
  nugetVersion: 0.3.0

init:
  - ps: Update-AppveyorBuild -Version $env:nugetVersion

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: $(nugetVersion)
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

image: Visual Studio 2017
configuration: Release
platform: Any CPU

before_build:
- nuget restore

build:
  verbosity: minimal
  
test: off

artifacts:
- path: '**\Seleniq*.nupkg'

for:
-
  branches:
      only:
        - develop
  version: 0.2.5.{build}
  environment:
    nugetVersion: 0.2.5-beta$(APPVEYOR_BUILD_NUMBER)